name:                reducible
version:             0.1.1.20221031
github:              "githubuser/reducible"
license:             BSD3
author:              "Evgeny Osipenko"
maintainer:          "evgeny.osipenko@metalamp.io"
copyright:           "2022 Evgeny Osipenko"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/reducible#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- exceptions
- mtl
- template-haskell
- transformers

library:
  source-dirs: src
  other-modules:
    - Control.Reducible.Internal.TH
    - Control.Reducible.Example
  ghc-options:
  - -Wall

tests:
  reducible-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reducible
    - QuickCheck
    - hspec
